### ISSUE TITLE
Lógica proposicional 

### ISSUE THREAD

**Issue by Nelson295281** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Nelson295281#1]
[LOGICA.PROPOSICIONAL1.1.pdf](https://github.com/user-attachments/files/17445774/LOGICA.PROPOSICIONAL1.1.pdf)

**Comment by Eddi3mendoz** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
